### PR TITLE
Add Yolov5End2End

### PR DESCRIPTION
**Pull request by ai-niki**
Hey there! I have added support for end2end tensorrt model with baked-in NMS. Though classes aren't super-thoughtfully designed and code has lower quality than the rest of the lib I decided to create the PR. Maybe this will give you inspiration to add end2end models support. Another option is to point me into the right direction to design & code this in a way that fits into the lib. If I have time I'll update the code and push a better version. Thanks for the great lib!

### CODE REVIEW

**Comment by ai-niki** [comment]
Here is the repo I've used to create end2end engines: https://github.com/triple-Mu/YOLO-TensorRT8

**Comment by mavihs7** [comment]
@pokidyshev Thanks for the great PR. we really appreciate it.  

@thegrogu owns the TensorRT code, I have requested a review from him.  He can also probably help with refactoring and design reviews if needed.  Thanks again!

From my side, I would recommend to check and fix the failing quality checks (which seems to be mostly white spaces) and document the code (function, class and module docstring)

**Comment by thegrogu** [comment]
@pokidyshev thanks for putting this together. I think this would be a great addition to the package. We could add ```end2end``` as an option while building the onnx model and for that I am thinking we need to update the ONNX and TensorRT conversion methods?

**Comment by ai-niki** [comment]
@thegrogu sounds good to me

**Comment by pokidyshev** [comment]
How do I configure proper auto formatting and linting in VS Code?

**Pull request closed without merging**
